// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdu6FkVeScLwrMxJRczFZdB9-wAH6-qJM',
    appId: '1:746800914584:web:feada0b0525229db3670ed',
    messagingSenderId: '746800914584',
    projectId: 'coalapp-f7e6b',
    authDomain: 'coalapp-f7e6b.firebaseapp.com',
    storageBucket: 'coalapp-f7e6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgyzU85tSouF5-JiHbEW4v2k10tBIXfck',
    appId: '1:746800914584:android:39094261885775ee3670ed',
    messagingSenderId: '746800914584',
    projectId: 'coalapp-f7e6b',
    storageBucket: 'coalapp-f7e6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLhzIbYaMWUBLirk2NkUdTmElF8ZTva8Q',
    appId: '1:746800914584:ios:b3b04fa7122f6f453670ed',
    messagingSenderId: '746800914584',
    projectId: 'coalapp-f7e6b',
    storageBucket: 'coalapp-f7e6b.appspot.com',
    iosBundleId: 'com.example.coalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLhzIbYaMWUBLirk2NkUdTmElF8ZTva8Q',
    appId: '1:746800914584:ios:b3b04fa7122f6f453670ed',
    messagingSenderId: '746800914584',
    projectId: 'coalapp-f7e6b',
    storageBucket: 'coalapp-f7e6b.appspot.com',
    iosBundleId: 'com.example.coalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdu6FkVeScLwrMxJRczFZdB9-wAH6-qJM',
    appId: '1:746800914584:web:f1c5f97a4186974c3670ed',
    messagingSenderId: '746800914584',
    projectId: 'coalapp-f7e6b',
    authDomain: 'coalapp-f7e6b.firebaseapp.com',
    storageBucket: 'coalapp-f7e6b.appspot.com',
  );
}
